"""some fixes

Revision ID: 07a811e432ce
Revises: 47f1020b7b6c
Create Date: 2025-01-26 00:14:52.730955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a811e432ce'
down_revision = '47f1020b7b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asistencias', schema=None) as batch_op:
        batch_op.alter_column('id_evento',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_usuario',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asistencias', schema=None) as batch_op:
        batch_op.alter_column('id_usuario',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_evento',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
