"""Se agrega tabla de Asistente

Revision ID: 77bc03590930
Revises: 6477f136ecfd
Create Date: 2025-01-23 12:48:17.051737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '77bc03590930'
down_revision = '6477f136ecfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asistencias',
    sa.Column('id_asistencia', sa.Integer(), nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('id_organizador', sa.Integer(), nullable=False),
    sa.Column('fecha_asistencia', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos.id_evento'], ),
    sa.ForeignKeyConstraint(['id_organizador'], ['organizadores.id_organizador'], ),
    sa.PrimaryKeyConstraint('id_asistencia')
    )
    op.drop_table('asistentes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asistentes',
    sa.Column('id_asistente', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('fecha_registro', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('eventos_registrados', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_asistente', name='asistentes_pkey'),
    sa.UniqueConstraint('email', name='asistentes_email_key')
    )
    op.drop_table('asistencias')
    # ### end Alembic commands ###
