"""Agregar relaciones en Asistentes

Revision ID: b6089801167e
Revises: be94da348224
Create Date: 2025-01-20 14:30:10.154810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6089801167e'
down_revision = 'be94da348224'
branch_labels = None
depends_on = None


def upgrade():
    # Agregar la columna con valor por defecto
    op.add_column('asistentes', sa.Column('id_evento', sa.Integer(), nullable=False, server_default='0'))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asistentes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_organizador')
        batch_op.drop_column('id_evento')

    # ### end Alembic commands ###
