"""Add gastos table

Revision ID: c434aae6e18c
Revises: f2498fb3eed3
Create Date: 2025-01-20 23:41:04.966794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c434aae6e18c'
down_revision = 'f2498fb3eed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gastos',
    sa.Column('id_gasto', sa.Integer(), nullable=False),
    sa.Column('id_evento', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('cantidad', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['id_evento'], ['eventos.id_evento'], ),
    sa.PrimaryKeyConstraint('id_gasto')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gastos')
    # ### end Alembic commands ###
